CREATE DATABASE YATSYNYK272
USE YATSYNYK272
CREATE TABLE EDUCATION (
id int  PRIMARY KEY,
education NVARCHAR(50),
year DATE
)
CREATE TABLE POSITION (
id int  PRIMARY KEY,
position NVARCHAR(50),
)
CREATE TABLE EMPLOYEE (
initials NVARCHAR(100) PRIMARY KEY ,
photo NVARCHAR(100),
position_id int  FOREIGN KEY REFERENCES POSITION(id),
chief NVARCHAR(100)  FOREIGN KEY REFERENCES EMPLOYEE(initials) ,
education_ID INT FOREIGN KEY REFERENCES EDUCATION(id),
experience int,
birthday DATETIME  CHECK(GETDATE() - birthday >=18),
adress NVARCHAR(256),
service_number NVARCHAR(10)  CHECK(service_number LIKE '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9]') ,
home_number NVARCHAR(15) CHECK(home_number LIKE '[0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9]'),
characteristic NVARCHAR(256),
)
CREATE TABLE PROMOTION_PENALTY (
initials_ID NVARCHAR(100) FOREIGN KEY REFERENCES EMPLOYEE(initials),
promotion_penalty NVARCHAR(256) PRIMARY KEY,
date DATE,
reason NVARCHAR(256),
position NVARCHAR(256)

)

CREATE TABLE PROMOTION_PENALTY (
initials_ID NVARCHAR(100) FOREIGN KEY REFERENCES EMPLOYEE(initials),
promotion_penalty NVARCHAR(256) PRIMARY KEY,
date DATE,
reason NVARCHAR(256),
position NVARCHAR(256)

)


INSERT INTO EMPLOYEE  VALUES ('ЯСА','photo1',1,'ЯСА',1,1,'1998-01-02','В.Лужок',null,null,'супер мужик')
INSERT INTO PROMOTION_PENALTY  VALUES ('ЯСА','Штраф 10 балів','2008-11-11','Підірвав гуртожиток','Студент')
INSERT INTO EDUCATION  VALUES (1,'ВИЩА','2008-11-11')
INSERT INTO POSITION  VALUES (1,'CEO')
SELECT * FROM PROMOTION_PENALTY
SELECT * FROM EMPLOYEE

DELETE FROM EMPLOYEE
DELETE FROM PROMOTION_PENALTY

DROP TABLE EMPLOYEE
DROP TABLE PROMOTION_PENALTY

DROP DATABASE YATSYNYK27

